### ISSUE TITLE
ObjectId to String

### ISSUE THREAD

**Issue by pdkhanh** [GhMartingit/xk6-mongo#1]
Hi there,

Thanks for a very great extension.
Can we have a method that converts the ObjectId to String

Because I need the ObjectId as String to do another query

Thanks

**Comment by GhMartingit** [comment]
Hi @pdkhanh,

Find methods return a bson document(s). You can manipulate the document however you like.

I'll close this ticket, but feel free to re-open it if you have other questions.

**Comment by pdkhanh** [comment]
hi @GhMartingit ,

thanks for your reply

I printed out the _id and it was a 12 bytes
somethings like [96,147,105,144,196,101,102,72,164,29,182,78]

how can I turn it to a String? like 507c7f79bcf86cd7994f6c0e
