### ISSUE TITLE
License for use

### ISSUE THREAD

**Issue by dazpoole** [GhMartingit/xk6-mongo#3]
Hi there, 

Just wondering if this extension is licensed under Apache-2.0 as detailed in the K6 documentation as the requirement for all extensions?
https://k6.io/docs/extensions/explanations/about-the-extensions-registry/#registry-requirements

If it is intended to be licensed as above, I'm just wondering if its possible for the LICENSE to be added to the repo? 

Thanks.

**Comment by GhMartingit** [comment]
License added
